services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=parking-lot
      - POSTGRES_PASSWORD=guest
      - POSTGRES_USER=guest
